[package]

name = "rust-snake"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
tags = []

[profile.dev]
opt-level = 2
debug = false

[profile.release]
opt-level = 2
debug = false

[[bin]]

name = "rust-snake"
path = "src/main.rs"

[dependencies.start_piston]

git = "https://github.com/bvssvni/start_piston.git"
features = ["include_gfx"]

