[package]

name = "rust-snake"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
tags = []

[profile.dev]
opt-level = 2
debug = false

[profile.release]
opt-level = 2
debug = false

[[bin]]

name = "rust-snake"
path = "src/main.rs"

[dependencies.sdl2_window]

git = "https://github.com/PistonDevelopers/sdl2_window.git"

[dependencies.gfx_graphics]

git = "https://github.com/PistonDevelopers/gfx_graphics.git"

[dependencies.opengl_graphics]

git = "https://github.com/PistonDevelopers/opengl_graphics.git"

[dependencies.fps_counter]

git = "https://github.com/PistonDevelopers/fps_counter"

